Add resources page
murilo-cunha/inteligencia-superficial pull request #3
Opened 2020-04-13 17:50 UTC by murilo-cunha

Added the resources page and corrected a couple of typos.

2020-04-13 19:36 UTC, molly-moon commented on _pages/about.md
>  Eu nasci em São Paulo, onde vivi até o colegial. De lá fui para os Estados Unidos, onde me formei em engenharia mecânica com concentração em mecatrônica. No meu último ano da faculdade, eu tive a opo
```suggestion
Eu nasci em São Paulo, onde vivi até o colegial. De lá fui para os Estados Unidos, onde me formei em engenharia mecânica com concentração em mecatrônica. No meu último ano da faculdade, eu tive a oportunidade de trabalhar em engenharia industrial. Foi lá que eu percebi que não era exatamente isso com o que eu queria fazer. Resolvi fazer um mestrado em inteligência artificial na Bélgica, onde moro hoje em dia.
```

2020-04-13 19:38 UTC, molly-moon commented on _pages/about.md
>  Eu nasci em São Paulo, onde vivi até o colegial. De lá fui para os Estados Unidos, onde me formei em engenharia mecânica com concentração em mecatrônica. No meu último ano da faculdade, eu tive a opo
```suggestion
Eu nasci em São Paulo, onde vivi até o colegial. De lá fui para os Estados Unidos, onde me formei em engenharia mecânica com concentração em mecatrônica. No meu último ano da faculdade, eu tive a oportunidade de trabalhar em engenharia industrial. Foi lá que eu percebi que não era exatamente isso com o que eu queria fazer. Resolvi fazer um mestrado em inteligência artificial na Bélgica, onde moro hoje em dia.
```

2020-04-13 21:17 UTC, alicjamazur requested changes

2020-04-13 21:17 UTC, alicjamazur commented on _pages/about.md
```suggestion
Eu nasci em São Paulo, onde vivi até o colegial. De lá fui para os Estados Unidos, onde me formei em engenharia mecânica com concentração em mecatrônica. No meu último ano da faculdade, eu tive a oportunidade de trabalhar em engenharia industrial. Foi lá que eu percebi que não era exatamente isso com o que eu queria fazer. Resolvi fazer um mestrado em inteligência artificial na Bélgica, onde moro hoje em dia.

```

2020-04-13 21:17 UTC, alicjamazur commented on _pages/resources.md
> +Aqui nós não abordamos temas importantes para alguém se interessa em botar esses conceitos em prática: cálculo, álgebra linear e programação. Apesar disso, queria listar aqui alguns recursos **gratui
```suggestion
Aqui nós não abordaremos de forma tão profunda temas como: cálculo, álgebra linear e programação. Apesar disso, queria listar aqui alguns recursos **gratuitos** que eu encontrei relacionados à eles, caso vocês queiram botar esses conceitos em prática.
```

2020-04-13 21:17 UTC, alicjamazur commented on _pages/resources.md
> +Eu listei abaixo alguns recursos que botam o conteúdo em ordem lógica, e mais estruturado, o que eu acho melhor pras pessoas que estão vendo isso pela primeira vez.
```suggestion
Eu listei abaixo alguns recursos que botam o conteúdo em ordem lógica, e mais estruturado, o que eu acho melhor para as pessoas que estão vendo isso pela primeira vez.
```

2020-04-13 21:17 UTC, alicjamazur commented on _pages/resources.md
> +* [Coursera/USP - parte 1][coursera_1] - curso de python (bom pra iniciantes)
```suggestion
* [Coursera/USP - parte 1][coursera_1] - curso de python (bom para iniciantes)
```

2020-04-13 21:17 UTC, alicjamazur commented on _pages/resources.md
> +* [Coursera/USP - parte 2][coursera_2] - curso de python (bom pra iniciantes)
```suggestion
* [Coursera/USP - parte 2][coursera_2] - curso de python (bom para iniciantes)
```

2020-04-14 18:56 UTC, murilo-cunha commented on _pages/about.md
Eu adicionei as mudancas!

2020-04-14 18:57 UTC, murilo-cunha commented on _pages/resources.md
> +Aqui nós não abordamos temas importantes para alguém se interessa em botar esses conceitos em prática: cálculo, álgebra linear e programação. Apesar disso, queria listar aqui alguns recursos **gratui
Achei que ficou bem melhor, mas eu mudei um pouquinho a segunda frase para "Apesar disso, queria listar aqui alguns recursos **gratuitos** que eu encontrei relacionados à eles, caso alguém queira aprender, praticar ou revisar." O que voce acha @molly-moon ?

2020-04-14 18:59 UTC, murilo-cunha commented
@molly-moon obrigado!! E desculpa que eu acabei fazendo uma confusao aqui.
Eu fiz todas as mudancas propostas acho. O que voce acha? Se tiver bom pode ate fechar o PR se quiser :)

2020-04-19 21:22 UTC, molly-moon commented on _pages/resources.md
> +Aqui nós não abordamos temas importantes para alguém se interessa em botar esses conceitos em prática: cálculo, álgebra linear e programação. Apesar disso, queria listar aqui alguns recursos **gratui
Beleza!

2020-04-19 21:23 UTC, alicjamazur approved these changes

2020-04-19 21:34 UTC, merged